"""
OSAdapter protocol — interface only.
Platform implementations live in macos.py and windows.py.
"""
from typing import Optional, Protocol


class OSAdapter(Protocol):
    def get_active_app(self) -> str: ...
    def get_window_title(self) -> str: ...
    def get_browser_url(self) -> str: ...
    def ocr_image(self, path: str) -> str: ...
    def read_credential(self) -> Optional[str]: ...
    def store_credential(self, token: str) -> None: ...
    def delete_credential(self, account: str) -> None: ...
    def check_screen_permission(self) -> bool: ...
    def request_screen_permission(self) -> str: ...   # 'GRANTED' or 'RESTART_REQUIRED'
    def open_permission_settings(self) -> None: ...
